package com.zhiao.blzc.test.entity;

import java.util.Date;

public class BbjDictinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbj_dictinfo.id
     *
     * @mbggenerated
     */
    private byte[] id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbj_dictinfo.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbj_dictinfo.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbj_dictinfo.update_by
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbj_dictinfo.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbj_dictinfo.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbj_dictinfo.del_flag
     *
     * @mbggenerated
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbj_dictinfo.pid
     *
     * @mbggenerated
     */
    private byte[] pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbj_dictinfo.dictcode
     *
     * @mbggenerated
     */
    private byte[] dictcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbj_dictinfo.dictname
     *
     * @mbggenerated
     */
    private byte[] dictname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbj_dictinfo.id
     *
     * @return the value of bbj_dictinfo.id
     *
     * @mbggenerated
     */
    public byte[] getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbj_dictinfo.id
     *
     * @param id the value for bbj_dictinfo.id
     *
     * @mbggenerated
     */
    public void setId(byte[] id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbj_dictinfo.create_by
     *
     * @return the value of bbj_dictinfo.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbj_dictinfo.create_by
     *
     * @param createBy the value for bbj_dictinfo.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbj_dictinfo.create_date
     *
     * @return the value of bbj_dictinfo.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbj_dictinfo.create_date
     *
     * @param createDate the value for bbj_dictinfo.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbj_dictinfo.update_by
     *
     * @return the value of bbj_dictinfo.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbj_dictinfo.update_by
     *
     * @param updateBy the value for bbj_dictinfo.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbj_dictinfo.update_date
     *
     * @return the value of bbj_dictinfo.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbj_dictinfo.update_date
     *
     * @param updateDate the value for bbj_dictinfo.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbj_dictinfo.remarks
     *
     * @return the value of bbj_dictinfo.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbj_dictinfo.remarks
     *
     * @param remarks the value for bbj_dictinfo.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbj_dictinfo.del_flag
     *
     * @return the value of bbj_dictinfo.del_flag
     *
     * @mbggenerated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbj_dictinfo.del_flag
     *
     * @param delFlag the value for bbj_dictinfo.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbj_dictinfo.pid
     *
     * @return the value of bbj_dictinfo.pid
     *
     * @mbggenerated
     */
    public byte[] getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbj_dictinfo.pid
     *
     * @param pid the value for bbj_dictinfo.pid
     *
     * @mbggenerated
     */
    public void setPid(byte[] pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbj_dictinfo.dictcode
     *
     * @return the value of bbj_dictinfo.dictcode
     *
     * @mbggenerated
     */
    public byte[] getDictcode() {
        return dictcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbj_dictinfo.dictcode
     *
     * @param dictcode the value for bbj_dictinfo.dictcode
     *
     * @mbggenerated
     */
    public void setDictcode(byte[] dictcode) {
        this.dictcode = dictcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbj_dictinfo.dictname
     *
     * @return the value of bbj_dictinfo.dictname
     *
     * @mbggenerated
     */
    public byte[] getDictname() {
        return dictname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbj_dictinfo.dictname
     *
     * @param dictname the value for bbj_dictinfo.dictname
     *
     * @mbggenerated
     */
    public void setDictname(byte[] dictname) {
        this.dictname = dictname;
    }
}