package com.zhiao.blzc.test.entity;

import java.util.Date;

public class BbjDicttype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbj_dicttype.id
     *
     * @mbggenerated
     */
    private byte[] id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbj_dicttype.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbj_dicttype.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbj_dicttype.update_by
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbj_dicttype.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbj_dicttype.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbj_dicttype.del_flag
     *
     * @mbggenerated
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbj_dicttype.typename
     *
     * @mbggenerated
     */
    private byte[] typename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbj_dicttype.id
     *
     * @return the value of bbj_dicttype.id
     *
     * @mbggenerated
     */
    public byte[] getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbj_dicttype.id
     *
     * @param id the value for bbj_dicttype.id
     *
     * @mbggenerated
     */
    public void setId(byte[] id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbj_dicttype.create_by
     *
     * @return the value of bbj_dicttype.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbj_dicttype.create_by
     *
     * @param createBy the value for bbj_dicttype.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbj_dicttype.create_date
     *
     * @return the value of bbj_dicttype.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbj_dicttype.create_date
     *
     * @param createDate the value for bbj_dicttype.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbj_dicttype.update_by
     *
     * @return the value of bbj_dicttype.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbj_dicttype.update_by
     *
     * @param updateBy the value for bbj_dicttype.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbj_dicttype.update_date
     *
     * @return the value of bbj_dicttype.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbj_dicttype.update_date
     *
     * @param updateDate the value for bbj_dicttype.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbj_dicttype.remarks
     *
     * @return the value of bbj_dicttype.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbj_dicttype.remarks
     *
     * @param remarks the value for bbj_dicttype.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbj_dicttype.del_flag
     *
     * @return the value of bbj_dicttype.del_flag
     *
     * @mbggenerated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbj_dicttype.del_flag
     *
     * @param delFlag the value for bbj_dicttype.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbj_dicttype.typename
     *
     * @return the value of bbj_dicttype.typename
     *
     * @mbggenerated
     */
    public byte[] getTypename() {
        return typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbj_dicttype.typename
     *
     * @param typename the value for bbj_dicttype.typename
     *
     * @mbggenerated
     */
    public void setTypename(byte[] typename) {
        this.typename = typename;
    }
}