package com.zhiao.blzc.test.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BbjZcPropertyPkgExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bbj_zc_property_pkg
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bbj_zc_property_pkg
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bbj_zc_property_pkg
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_zc_property_pkg
     *
     * @mbggenerated
     */
    public BbjZcPropertyPkgExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_zc_property_pkg
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_zc_property_pkg
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_zc_property_pkg
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_zc_property_pkg
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_zc_property_pkg
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_zc_property_pkg
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_zc_property_pkg
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_zc_property_pkg
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_zc_property_pkg
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_zc_property_pkg
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bbj_zc_property_pkg
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(byte[] value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(byte[] value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(byte[] value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(byte[] value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(byte[] value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(byte[] value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<byte[]> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<byte[]> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(byte[] value1, byte[] value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(byte[] value1, byte[] value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPrincipalBalanceIsNull() {
            addCriterion("principal_balance is null");
            return (Criteria) this;
        }

        public Criteria andPrincipalBalanceIsNotNull() {
            addCriterion("principal_balance is not null");
            return (Criteria) this;
        }

        public Criteria andPrincipalBalanceEqualTo(Long value) {
            addCriterion("principal_balance =", value, "principalBalance");
            return (Criteria) this;
        }

        public Criteria andPrincipalBalanceNotEqualTo(Long value) {
            addCriterion("principal_balance <>", value, "principalBalance");
            return (Criteria) this;
        }

        public Criteria andPrincipalBalanceGreaterThan(Long value) {
            addCriterion("principal_balance >", value, "principalBalance");
            return (Criteria) this;
        }

        public Criteria andPrincipalBalanceGreaterThanOrEqualTo(Long value) {
            addCriterion("principal_balance >=", value, "principalBalance");
            return (Criteria) this;
        }

        public Criteria andPrincipalBalanceLessThan(Long value) {
            addCriterion("principal_balance <", value, "principalBalance");
            return (Criteria) this;
        }

        public Criteria andPrincipalBalanceLessThanOrEqualTo(Long value) {
            addCriterion("principal_balance <=", value, "principalBalance");
            return (Criteria) this;
        }

        public Criteria andPrincipalBalanceIn(List<Long> values) {
            addCriterion("principal_balance in", values, "principalBalance");
            return (Criteria) this;
        }

        public Criteria andPrincipalBalanceNotIn(List<Long> values) {
            addCriterion("principal_balance not in", values, "principalBalance");
            return (Criteria) this;
        }

        public Criteria andPrincipalBalanceBetween(Long value1, Long value2) {
            addCriterion("principal_balance between", value1, value2, "principalBalance");
            return (Criteria) this;
        }

        public Criteria andPrincipalBalanceNotBetween(Long value1, Long value2) {
            addCriterion("principal_balance not between", value1, value2, "principalBalance");
            return (Criteria) this;
        }

        public Criteria andInterestIsNull() {
            addCriterion("interest is null");
            return (Criteria) this;
        }

        public Criteria andInterestIsNotNull() {
            addCriterion("interest is not null");
            return (Criteria) this;
        }

        public Criteria andInterestEqualTo(Double value) {
            addCriterion("interest =", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestNotEqualTo(Double value) {
            addCriterion("interest <>", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestGreaterThan(Double value) {
            addCriterion("interest >", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestGreaterThanOrEqualTo(Double value) {
            addCriterion("interest >=", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestLessThan(Double value) {
            addCriterion("interest <", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestLessThanOrEqualTo(Double value) {
            addCriterion("interest <=", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestIn(List<Double> values) {
            addCriterion("interest in", values, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestNotIn(List<Double> values) {
            addCriterion("interest not in", values, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestBetween(Double value1, Double value2) {
            addCriterion("interest between", value1, value2, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestNotBetween(Double value1, Double value2) {
            addCriterion("interest not between", value1, value2, "interest");
            return (Criteria) this;
        }

        public Criteria andSotoppiIsNull() {
            addCriterion("sotoppi is null");
            return (Criteria) this;
        }

        public Criteria andSotoppiIsNotNull() {
            addCriterion("sotoppi is not null");
            return (Criteria) this;
        }

        public Criteria andSotoppiEqualTo(Long value) {
            addCriterion("sotoppi =", value, "sotoppi");
            return (Criteria) this;
        }

        public Criteria andSotoppiNotEqualTo(Long value) {
            addCriterion("sotoppi <>", value, "sotoppi");
            return (Criteria) this;
        }

        public Criteria andSotoppiGreaterThan(Long value) {
            addCriterion("sotoppi >", value, "sotoppi");
            return (Criteria) this;
        }

        public Criteria andSotoppiGreaterThanOrEqualTo(Long value) {
            addCriterion("sotoppi >=", value, "sotoppi");
            return (Criteria) this;
        }

        public Criteria andSotoppiLessThan(Long value) {
            addCriterion("sotoppi <", value, "sotoppi");
            return (Criteria) this;
        }

        public Criteria andSotoppiLessThanOrEqualTo(Long value) {
            addCriterion("sotoppi <=", value, "sotoppi");
            return (Criteria) this;
        }

        public Criteria andSotoppiIn(List<Long> values) {
            addCriterion("sotoppi in", values, "sotoppi");
            return (Criteria) this;
        }

        public Criteria andSotoppiNotIn(List<Long> values) {
            addCriterion("sotoppi not in", values, "sotoppi");
            return (Criteria) this;
        }

        public Criteria andSotoppiBetween(Long value1, Long value2) {
            addCriterion("sotoppi between", value1, value2, "sotoppi");
            return (Criteria) this;
        }

        public Criteria andSotoppiNotBetween(Long value1, Long value2) {
            addCriterion("sotoppi not between", value1, value2, "sotoppi");
            return (Criteria) this;
        }

        public Criteria andInterestAccrualEndtimeIsNull() {
            addCriterion("interest_accrual_endtime is null");
            return (Criteria) this;
        }

        public Criteria andInterestAccrualEndtimeIsNotNull() {
            addCriterion("interest_accrual_endtime is not null");
            return (Criteria) this;
        }

        public Criteria andInterestAccrualEndtimeEqualTo(Date value) {
            addCriterion("interest_accrual_endtime =", value, "interestAccrualEndtime");
            return (Criteria) this;
        }

        public Criteria andInterestAccrualEndtimeNotEqualTo(Date value) {
            addCriterion("interest_accrual_endtime <>", value, "interestAccrualEndtime");
            return (Criteria) this;
        }

        public Criteria andInterestAccrualEndtimeGreaterThan(Date value) {
            addCriterion("interest_accrual_endtime >", value, "interestAccrualEndtime");
            return (Criteria) this;
        }

        public Criteria andInterestAccrualEndtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("interest_accrual_endtime >=", value, "interestAccrualEndtime");
            return (Criteria) this;
        }

        public Criteria andInterestAccrualEndtimeLessThan(Date value) {
            addCriterion("interest_accrual_endtime <", value, "interestAccrualEndtime");
            return (Criteria) this;
        }

        public Criteria andInterestAccrualEndtimeLessThanOrEqualTo(Date value) {
            addCriterion("interest_accrual_endtime <=", value, "interestAccrualEndtime");
            return (Criteria) this;
        }

        public Criteria andInterestAccrualEndtimeIn(List<Date> values) {
            addCriterion("interest_accrual_endtime in", values, "interestAccrualEndtime");
            return (Criteria) this;
        }

        public Criteria andInterestAccrualEndtimeNotIn(List<Date> values) {
            addCriterion("interest_accrual_endtime not in", values, "interestAccrualEndtime");
            return (Criteria) this;
        }

        public Criteria andInterestAccrualEndtimeBetween(Date value1, Date value2) {
            addCriterion("interest_accrual_endtime between", value1, value2, "interestAccrualEndtime");
            return (Criteria) this;
        }

        public Criteria andInterestAccrualEndtimeNotBetween(Date value1, Date value2) {
            addCriterion("interest_accrual_endtime not between", value1, value2, "interestAccrualEndtime");
            return (Criteria) this;
        }

        public Criteria andCsOuttimeIsNull() {
            addCriterion("cs_outtime is null");
            return (Criteria) this;
        }

        public Criteria andCsOuttimeIsNotNull() {
            addCriterion("cs_outtime is not null");
            return (Criteria) this;
        }

        public Criteria andCsOuttimeEqualTo(Date value) {
            addCriterion("cs_outtime =", value, "csOuttime");
            return (Criteria) this;
        }

        public Criteria andCsOuttimeNotEqualTo(Date value) {
            addCriterion("cs_outtime <>", value, "csOuttime");
            return (Criteria) this;
        }

        public Criteria andCsOuttimeGreaterThan(Date value) {
            addCriterion("cs_outtime >", value, "csOuttime");
            return (Criteria) this;
        }

        public Criteria andCsOuttimeGreaterThanOrEqualTo(Date value) {
            addCriterion("cs_outtime >=", value, "csOuttime");
            return (Criteria) this;
        }

        public Criteria andCsOuttimeLessThan(Date value) {
            addCriterion("cs_outtime <", value, "csOuttime");
            return (Criteria) this;
        }

        public Criteria andCsOuttimeLessThanOrEqualTo(Date value) {
            addCriterion("cs_outtime <=", value, "csOuttime");
            return (Criteria) this;
        }

        public Criteria andCsOuttimeIn(List<Date> values) {
            addCriterion("cs_outtime in", values, "csOuttime");
            return (Criteria) this;
        }

        public Criteria andCsOuttimeNotIn(List<Date> values) {
            addCriterion("cs_outtime not in", values, "csOuttime");
            return (Criteria) this;
        }

        public Criteria andCsOuttimeBetween(Date value1, Date value2) {
            addCriterion("cs_outtime between", value1, value2, "csOuttime");
            return (Criteria) this;
        }

        public Criteria andCsOuttimeNotBetween(Date value1, Date value2) {
            addCriterion("cs_outtime not between", value1, value2, "csOuttime");
            return (Criteria) this;
        }

        public Criteria andCsCtimeIsNull() {
            addCriterion("cs_ctime is null");
            return (Criteria) this;
        }

        public Criteria andCsCtimeIsNotNull() {
            addCriterion("cs_ctime is not null");
            return (Criteria) this;
        }

        public Criteria andCsCtimeEqualTo(Date value) {
            addCriterion("cs_ctime =", value, "csCtime");
            return (Criteria) this;
        }

        public Criteria andCsCtimeNotEqualTo(Date value) {
            addCriterion("cs_ctime <>", value, "csCtime");
            return (Criteria) this;
        }

        public Criteria andCsCtimeGreaterThan(Date value) {
            addCriterion("cs_ctime >", value, "csCtime");
            return (Criteria) this;
        }

        public Criteria andCsCtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("cs_ctime >=", value, "csCtime");
            return (Criteria) this;
        }

        public Criteria andCsCtimeLessThan(Date value) {
            addCriterion("cs_ctime <", value, "csCtime");
            return (Criteria) this;
        }

        public Criteria andCsCtimeLessThanOrEqualTo(Date value) {
            addCriterion("cs_ctime <=", value, "csCtime");
            return (Criteria) this;
        }

        public Criteria andCsCtimeIn(List<Date> values) {
            addCriterion("cs_ctime in", values, "csCtime");
            return (Criteria) this;
        }

        public Criteria andCsCtimeNotIn(List<Date> values) {
            addCriterion("cs_ctime not in", values, "csCtime");
            return (Criteria) this;
        }

        public Criteria andCsCtimeBetween(Date value1, Date value2) {
            addCriterion("cs_ctime between", value1, value2, "csCtime");
            return (Criteria) this;
        }

        public Criteria andCsCtimeNotBetween(Date value1, Date value2) {
            addCriterion("cs_ctime not between", value1, value2, "csCtime");
            return (Criteria) this;
        }

        public Criteria andTransferorOutimeIsNull() {
            addCriterion("transferor_outime is null");
            return (Criteria) this;
        }

        public Criteria andTransferorOutimeIsNotNull() {
            addCriterion("transferor_outime is not null");
            return (Criteria) this;
        }

        public Criteria andTransferorOutimeEqualTo(Date value) {
            addCriterion("transferor_outime =", value, "transferorOutime");
            return (Criteria) this;
        }

        public Criteria andTransferorOutimeNotEqualTo(Date value) {
            addCriterion("transferor_outime <>", value, "transferorOutime");
            return (Criteria) this;
        }

        public Criteria andTransferorOutimeGreaterThan(Date value) {
            addCriterion("transferor_outime >", value, "transferorOutime");
            return (Criteria) this;
        }

        public Criteria andTransferorOutimeGreaterThanOrEqualTo(Date value) {
            addCriterion("transferor_outime >=", value, "transferorOutime");
            return (Criteria) this;
        }

        public Criteria andTransferorOutimeLessThan(Date value) {
            addCriterion("transferor_outime <", value, "transferorOutime");
            return (Criteria) this;
        }

        public Criteria andTransferorOutimeLessThanOrEqualTo(Date value) {
            addCriterion("transferor_outime <=", value, "transferorOutime");
            return (Criteria) this;
        }

        public Criteria andTransferorOutimeIn(List<Date> values) {
            addCriterion("transferor_outime in", values, "transferorOutime");
            return (Criteria) this;
        }

        public Criteria andTransferorOutimeNotIn(List<Date> values) {
            addCriterion("transferor_outime not in", values, "transferorOutime");
            return (Criteria) this;
        }

        public Criteria andTransferorOutimeBetween(Date value1, Date value2) {
            addCriterion("transferor_outime between", value1, value2, "transferorOutime");
            return (Criteria) this;
        }

        public Criteria andTransferorOutimeNotBetween(Date value1, Date value2) {
            addCriterion("transferor_outime not between", value1, value2, "transferorOutime");
            return (Criteria) this;
        }

        public Criteria andAocrLyIsNull() {
            addCriterion("aocr_ly is null");
            return (Criteria) this;
        }

        public Criteria andAocrLyIsNotNull() {
            addCriterion("aocr_ly is not null");
            return (Criteria) this;
        }

        public Criteria andAocrLyEqualTo(Long value) {
            addCriterion("aocr_ly =", value, "aocrLy");
            return (Criteria) this;
        }

        public Criteria andAocrLyNotEqualTo(Long value) {
            addCriterion("aocr_ly <>", value, "aocrLy");
            return (Criteria) this;
        }

        public Criteria andAocrLyGreaterThan(Long value) {
            addCriterion("aocr_ly >", value, "aocrLy");
            return (Criteria) this;
        }

        public Criteria andAocrLyGreaterThanOrEqualTo(Long value) {
            addCriterion("aocr_ly >=", value, "aocrLy");
            return (Criteria) this;
        }

        public Criteria andAocrLyLessThan(Long value) {
            addCriterion("aocr_ly <", value, "aocrLy");
            return (Criteria) this;
        }

        public Criteria andAocrLyLessThanOrEqualTo(Long value) {
            addCriterion("aocr_ly <=", value, "aocrLy");
            return (Criteria) this;
        }

        public Criteria andAocrLyIn(List<Long> values) {
            addCriterion("aocr_ly in", values, "aocrLy");
            return (Criteria) this;
        }

        public Criteria andAocrLyNotIn(List<Long> values) {
            addCriterion("aocr_ly not in", values, "aocrLy");
            return (Criteria) this;
        }

        public Criteria andAocrLyBetween(Long value1, Long value2) {
            addCriterion("aocr_ly between", value1, value2, "aocrLy");
            return (Criteria) this;
        }

        public Criteria andAocrLyNotBetween(Long value1, Long value2) {
            addCriterion("aocr_ly not between", value1, value2, "aocrLy");
            return (Criteria) this;
        }

        public Criteria andAocrTyIsNull() {
            addCriterion("aocr_ty is null");
            return (Criteria) this;
        }

        public Criteria andAocrTyIsNotNull() {
            addCriterion("aocr_ty is not null");
            return (Criteria) this;
        }

        public Criteria andAocrTyEqualTo(Long value) {
            addCriterion("aocr_ty =", value, "aocrTy");
            return (Criteria) this;
        }

        public Criteria andAocrTyNotEqualTo(Long value) {
            addCriterion("aocr_ty <>", value, "aocrTy");
            return (Criteria) this;
        }

        public Criteria andAocrTyGreaterThan(Long value) {
            addCriterion("aocr_ty >", value, "aocrTy");
            return (Criteria) this;
        }

        public Criteria andAocrTyGreaterThanOrEqualTo(Long value) {
            addCriterion("aocr_ty >=", value, "aocrTy");
            return (Criteria) this;
        }

        public Criteria andAocrTyLessThan(Long value) {
            addCriterion("aocr_ty <", value, "aocrTy");
            return (Criteria) this;
        }

        public Criteria andAocrTyLessThanOrEqualTo(Long value) {
            addCriterion("aocr_ty <=", value, "aocrTy");
            return (Criteria) this;
        }

        public Criteria andAocrTyIn(List<Long> values) {
            addCriterion("aocr_ty in", values, "aocrTy");
            return (Criteria) this;
        }

        public Criteria andAocrTyNotIn(List<Long> values) {
            addCriterion("aocr_ty not in", values, "aocrTy");
            return (Criteria) this;
        }

        public Criteria andAocrTyBetween(Long value1, Long value2) {
            addCriterion("aocr_ty between", value1, value2, "aocrTy");
            return (Criteria) this;
        }

        public Criteria andAocrTyNotBetween(Long value1, Long value2) {
            addCriterion("aocr_ty not between", value1, value2, "aocrTy");
            return (Criteria) this;
        }

        public Criteria andAnnualReturnTargetIsNull() {
            addCriterion("annual_return_target is null");
            return (Criteria) this;
        }

        public Criteria andAnnualReturnTargetIsNotNull() {
            addCriterion("annual_return_target is not null");
            return (Criteria) this;
        }

        public Criteria andAnnualReturnTargetEqualTo(String value) {
            addCriterion("annual_return_target =", value, "annualReturnTarget");
            return (Criteria) this;
        }

        public Criteria andAnnualReturnTargetNotEqualTo(String value) {
            addCriterion("annual_return_target <>", value, "annualReturnTarget");
            return (Criteria) this;
        }

        public Criteria andAnnualReturnTargetGreaterThan(String value) {
            addCriterion("annual_return_target >", value, "annualReturnTarget");
            return (Criteria) this;
        }

        public Criteria andAnnualReturnTargetGreaterThanOrEqualTo(String value) {
            addCriterion("annual_return_target >=", value, "annualReturnTarget");
            return (Criteria) this;
        }

        public Criteria andAnnualReturnTargetLessThan(String value) {
            addCriterion("annual_return_target <", value, "annualReturnTarget");
            return (Criteria) this;
        }

        public Criteria andAnnualReturnTargetLessThanOrEqualTo(String value) {
            addCriterion("annual_return_target <=", value, "annualReturnTarget");
            return (Criteria) this;
        }

        public Criteria andAnnualReturnTargetLike(String value) {
            addCriterion("annual_return_target like", value, "annualReturnTarget");
            return (Criteria) this;
        }

        public Criteria andAnnualReturnTargetNotLike(String value) {
            addCriterion("annual_return_target not like", value, "annualReturnTarget");
            return (Criteria) this;
        }

        public Criteria andAnnualReturnTargetIn(List<String> values) {
            addCriterion("annual_return_target in", values, "annualReturnTarget");
            return (Criteria) this;
        }

        public Criteria andAnnualReturnTargetNotIn(List<String> values) {
            addCriterion("annual_return_target not in", values, "annualReturnTarget");
            return (Criteria) this;
        }

        public Criteria andAnnualReturnTargetBetween(String value1, String value2) {
            addCriterion("annual_return_target between", value1, value2, "annualReturnTarget");
            return (Criteria) this;
        }

        public Criteria andAnnualReturnTargetNotBetween(String value1, String value2) {
            addCriterion("annual_return_target not between", value1, value2, "annualReturnTarget");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNull() {
            addCriterion("create_by is null");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNotNull() {
            addCriterion("create_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByEqualTo(String value) {
            addCriterion("create_by =", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotEqualTo(String value) {
            addCriterion("create_by <>", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThan(String value) {
            addCriterion("create_by >", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThanOrEqualTo(String value) {
            addCriterion("create_by >=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThan(String value) {
            addCriterion("create_by <", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThanOrEqualTo(String value) {
            addCriterion("create_by <=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLike(String value) {
            addCriterion("create_by like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotLike(String value) {
            addCriterion("create_by not like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByIn(List<String> values) {
            addCriterion("create_by in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotIn(List<String> values) {
            addCriterion("create_by not in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByBetween(String value1, String value2) {
            addCriterion("create_by between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotBetween(String value1, String value2) {
            addCriterion("create_by not between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNull() {
            addCriterion("update_by is null");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNotNull() {
            addCriterion("update_by is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateByEqualTo(String value) {
            addCriterion("update_by =", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotEqualTo(String value) {
            addCriterion("update_by <>", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThan(String value) {
            addCriterion("update_by >", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThanOrEqualTo(String value) {
            addCriterion("update_by >=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThan(String value) {
            addCriterion("update_by <", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThanOrEqualTo(String value) {
            addCriterion("update_by <=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLike(String value) {
            addCriterion("update_by like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotLike(String value) {
            addCriterion("update_by not like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByIn(List<String> values) {
            addCriterion("update_by in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotIn(List<String> values) {
            addCriterion("update_by not in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByBetween(String value1, String value2) {
            addCriterion("update_by between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotBetween(String value1, String value2) {
            addCriterion("update_by not between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNull() {
            addCriterion("remarks is null");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNotNull() {
            addCriterion("remarks is not null");
            return (Criteria) this;
        }

        public Criteria andRemarksEqualTo(String value) {
            addCriterion("remarks =", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotEqualTo(String value) {
            addCriterion("remarks <>", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThan(String value) {
            addCriterion("remarks >", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("remarks >=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThan(String value) {
            addCriterion("remarks <", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThanOrEqualTo(String value) {
            addCriterion("remarks <=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLike(String value) {
            addCriterion("remarks like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotLike(String value) {
            addCriterion("remarks not like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksIn(List<String> values) {
            addCriterion("remarks in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotIn(List<String> values) {
            addCriterion("remarks not in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksBetween(String value1, String value2) {
            addCriterion("remarks between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotBetween(String value1, String value2) {
            addCriterion("remarks not between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNull() {
            addCriterion("del_flag is null");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNotNull() {
            addCriterion("del_flag is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlagEqualTo(String value) {
            addCriterion("del_flag =", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotEqualTo(String value) {
            addCriterion("del_flag <>", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThan(String value) {
            addCriterion("del_flag >", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThanOrEqualTo(String value) {
            addCriterion("del_flag >=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThan(String value) {
            addCriterion("del_flag <", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThanOrEqualTo(String value) {
            addCriterion("del_flag <=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLike(String value) {
            addCriterion("del_flag like", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotLike(String value) {
            addCriterion("del_flag not like", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagIn(List<String> values) {
            addCriterion("del_flag in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotIn(List<String> values) {
            addCriterion("del_flag not in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagBetween(String value1, String value2) {
            addCriterion("del_flag between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotBetween(String value1, String value2) {
            addCriterion("del_flag not between", value1, value2, "delFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bbj_zc_property_pkg
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bbj_zc_property_pkg
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}