package com.zhiao.blzc.test.entity;

import java.util.Date;

public class BbjZcPropertyPkg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbj_zc_property_pkg.id
     *
     * @mbggenerated
     */
    private byte[] id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbj_zc_property_pkg.principal_balance
     *
     * @mbggenerated
     */
    private Long principalBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbj_zc_property_pkg.interest
     *
     * @mbggenerated
     */
    private Double interest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbj_zc_property_pkg.sotoppi
     *
     * @mbggenerated
     */
    private Long sotoppi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbj_zc_property_pkg.interest_accrual_endtime
     *
     * @mbggenerated
     */
    private Date interestAccrualEndtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbj_zc_property_pkg.cs_outtime
     *
     * @mbggenerated
     */
    private Date csOuttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbj_zc_property_pkg.cs_ctime
     *
     * @mbggenerated
     */
    private Date csCtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbj_zc_property_pkg.transferor_outime
     *
     * @mbggenerated
     */
    private Date transferorOutime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbj_zc_property_pkg.aocr_ly
     *
     * @mbggenerated
     */
    private Long aocrLy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbj_zc_property_pkg.aocr_ty
     *
     * @mbggenerated
     */
    private Long aocrTy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbj_zc_property_pkg.annual_return_target
     *
     * @mbggenerated
     */
    private String annualReturnTarget;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbj_zc_property_pkg.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbj_zc_property_pkg.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbj_zc_property_pkg.update_by
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbj_zc_property_pkg.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbj_zc_property_pkg.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbj_zc_property_pkg.del_flag
     *
     * @mbggenerated
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbj_zc_property_pkg.loan_origination
     *
     * @mbggenerated
     */
    private byte[] loanOrigination;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbj_zc_property_pkg.transferor
     *
     * @mbggenerated
     */
    private byte[] transferor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbj_zc_property_pkg.holder
     *
     * @mbggenerated
     */
    private byte[] holder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbj_zc_property_pkg.id
     *
     * @return the value of bbj_zc_property_pkg.id
     *
     * @mbggenerated
     */
    public byte[] getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbj_zc_property_pkg.id
     *
     * @param id the value for bbj_zc_property_pkg.id
     *
     * @mbggenerated
     */
    public void setId(byte[] id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbj_zc_property_pkg.principal_balance
     *
     * @return the value of bbj_zc_property_pkg.principal_balance
     *
     * @mbggenerated
     */
    public Long getPrincipalBalance() {
        return principalBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbj_zc_property_pkg.principal_balance
     *
     * @param principalBalance the value for bbj_zc_property_pkg.principal_balance
     *
     * @mbggenerated
     */
    public void setPrincipalBalance(Long principalBalance) {
        this.principalBalance = principalBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbj_zc_property_pkg.interest
     *
     * @return the value of bbj_zc_property_pkg.interest
     *
     * @mbggenerated
     */
    public Double getInterest() {
        return interest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbj_zc_property_pkg.interest
     *
     * @param interest the value for bbj_zc_property_pkg.interest
     *
     * @mbggenerated
     */
    public void setInterest(Double interest) {
        this.interest = interest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbj_zc_property_pkg.sotoppi
     *
     * @return the value of bbj_zc_property_pkg.sotoppi
     *
     * @mbggenerated
     */
    public Long getSotoppi() {
        return sotoppi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbj_zc_property_pkg.sotoppi
     *
     * @param sotoppi the value for bbj_zc_property_pkg.sotoppi
     *
     * @mbggenerated
     */
    public void setSotoppi(Long sotoppi) {
        this.sotoppi = sotoppi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbj_zc_property_pkg.interest_accrual_endtime
     *
     * @return the value of bbj_zc_property_pkg.interest_accrual_endtime
     *
     * @mbggenerated
     */
    public Date getInterestAccrualEndtime() {
        return interestAccrualEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbj_zc_property_pkg.interest_accrual_endtime
     *
     * @param interestAccrualEndtime the value for bbj_zc_property_pkg.interest_accrual_endtime
     *
     * @mbggenerated
     */
    public void setInterestAccrualEndtime(Date interestAccrualEndtime) {
        this.interestAccrualEndtime = interestAccrualEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbj_zc_property_pkg.cs_outtime
     *
     * @return the value of bbj_zc_property_pkg.cs_outtime
     *
     * @mbggenerated
     */
    public Date getCsOuttime() {
        return csOuttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbj_zc_property_pkg.cs_outtime
     *
     * @param csOuttime the value for bbj_zc_property_pkg.cs_outtime
     *
     * @mbggenerated
     */
    public void setCsOuttime(Date csOuttime) {
        this.csOuttime = csOuttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbj_zc_property_pkg.cs_ctime
     *
     * @return the value of bbj_zc_property_pkg.cs_ctime
     *
     * @mbggenerated
     */
    public Date getCsCtime() {
        return csCtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbj_zc_property_pkg.cs_ctime
     *
     * @param csCtime the value for bbj_zc_property_pkg.cs_ctime
     *
     * @mbggenerated
     */
    public void setCsCtime(Date csCtime) {
        this.csCtime = csCtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbj_zc_property_pkg.transferor_outime
     *
     * @return the value of bbj_zc_property_pkg.transferor_outime
     *
     * @mbggenerated
     */
    public Date getTransferorOutime() {
        return transferorOutime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbj_zc_property_pkg.transferor_outime
     *
     * @param transferorOutime the value for bbj_zc_property_pkg.transferor_outime
     *
     * @mbggenerated
     */
    public void setTransferorOutime(Date transferorOutime) {
        this.transferorOutime = transferorOutime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbj_zc_property_pkg.aocr_ly
     *
     * @return the value of bbj_zc_property_pkg.aocr_ly
     *
     * @mbggenerated
     */
    public Long getAocrLy() {
        return aocrLy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbj_zc_property_pkg.aocr_ly
     *
     * @param aocrLy the value for bbj_zc_property_pkg.aocr_ly
     *
     * @mbggenerated
     */
    public void setAocrLy(Long aocrLy) {
        this.aocrLy = aocrLy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbj_zc_property_pkg.aocr_ty
     *
     * @return the value of bbj_zc_property_pkg.aocr_ty
     *
     * @mbggenerated
     */
    public Long getAocrTy() {
        return aocrTy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbj_zc_property_pkg.aocr_ty
     *
     * @param aocrTy the value for bbj_zc_property_pkg.aocr_ty
     *
     * @mbggenerated
     */
    public void setAocrTy(Long aocrTy) {
        this.aocrTy = aocrTy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbj_zc_property_pkg.annual_return_target
     *
     * @return the value of bbj_zc_property_pkg.annual_return_target
     *
     * @mbggenerated
     */
    public String getAnnualReturnTarget() {
        return annualReturnTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbj_zc_property_pkg.annual_return_target
     *
     * @param annualReturnTarget the value for bbj_zc_property_pkg.annual_return_target
     *
     * @mbggenerated
     */
    public void setAnnualReturnTarget(String annualReturnTarget) {
        this.annualReturnTarget = annualReturnTarget == null ? null : annualReturnTarget.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbj_zc_property_pkg.create_by
     *
     * @return the value of bbj_zc_property_pkg.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbj_zc_property_pkg.create_by
     *
     * @param createBy the value for bbj_zc_property_pkg.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbj_zc_property_pkg.create_date
     *
     * @return the value of bbj_zc_property_pkg.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbj_zc_property_pkg.create_date
     *
     * @param createDate the value for bbj_zc_property_pkg.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbj_zc_property_pkg.update_by
     *
     * @return the value of bbj_zc_property_pkg.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbj_zc_property_pkg.update_by
     *
     * @param updateBy the value for bbj_zc_property_pkg.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbj_zc_property_pkg.update_date
     *
     * @return the value of bbj_zc_property_pkg.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbj_zc_property_pkg.update_date
     *
     * @param updateDate the value for bbj_zc_property_pkg.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbj_zc_property_pkg.remarks
     *
     * @return the value of bbj_zc_property_pkg.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbj_zc_property_pkg.remarks
     *
     * @param remarks the value for bbj_zc_property_pkg.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbj_zc_property_pkg.del_flag
     *
     * @return the value of bbj_zc_property_pkg.del_flag
     *
     * @mbggenerated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbj_zc_property_pkg.del_flag
     *
     * @param delFlag the value for bbj_zc_property_pkg.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbj_zc_property_pkg.loan_origination
     *
     * @return the value of bbj_zc_property_pkg.loan_origination
     *
     * @mbggenerated
     */
    public byte[] getLoanOrigination() {
        return loanOrigination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbj_zc_property_pkg.loan_origination
     *
     * @param loanOrigination the value for bbj_zc_property_pkg.loan_origination
     *
     * @mbggenerated
     */
    public void setLoanOrigination(byte[] loanOrigination) {
        this.loanOrigination = loanOrigination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbj_zc_property_pkg.transferor
     *
     * @return the value of bbj_zc_property_pkg.transferor
     *
     * @mbggenerated
     */
    public byte[] getTransferor() {
        return transferor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbj_zc_property_pkg.transferor
     *
     * @param transferor the value for bbj_zc_property_pkg.transferor
     *
     * @mbggenerated
     */
    public void setTransferor(byte[] transferor) {
        this.transferor = transferor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbj_zc_property_pkg.holder
     *
     * @return the value of bbj_zc_property_pkg.holder
     *
     * @mbggenerated
     */
    public byte[] getHolder() {
        return holder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbj_zc_property_pkg.holder
     *
     * @param holder the value for bbj_zc_property_pkg.holder
     *
     * @mbggenerated
     */
    public void setHolder(byte[] holder) {
        this.holder = holder;
    }
}