package com.zhiao.blzc.test.dao;

import com.zhiao.blzc.test.entity.BbjDicttype;
import com.zhiao.blzc.test.entity.BbjDicttypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BbjDicttypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_dicttype
     *
     * @mbggenerated
     */
    int countByExample(BbjDicttypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_dicttype
     *
     * @mbggenerated
     */
    int deleteByExample(BbjDicttypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_dicttype
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(byte[] id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_dicttype
     *
     * @mbggenerated
     */
    int insert(BbjDicttype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_dicttype
     *
     * @mbggenerated
     */
    int insertSelective(BbjDicttype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_dicttype
     *
     * @mbggenerated
     */
    List<BbjDicttype> selectByExampleWithBLOBs(BbjDicttypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_dicttype
     *
     * @mbggenerated
     */
    List<BbjDicttype> selectByExample(BbjDicttypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_dicttype
     *
     * @mbggenerated
     */
    BbjDicttype selectByPrimaryKey(byte[] id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_dicttype
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BbjDicttype record, @Param("example") BbjDicttypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_dicttype
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") BbjDicttype record, @Param("example") BbjDicttypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_dicttype
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BbjDicttype record, @Param("example") BbjDicttypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_dicttype
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BbjDicttype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_dicttype
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(BbjDicttype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_dicttype
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BbjDicttype record);
}