package com.zhiao.blzc.test.dao;

import com.zhiao.blzc.test.entity.BbjDictinfo;
import com.zhiao.blzc.test.entity.BbjDictinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BbjDictinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_dictinfo
     *
     * @mbggenerated
     */
    int countByExample(BbjDictinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_dictinfo
     *
     * @mbggenerated
     */
    int deleteByExample(BbjDictinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_dictinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(byte[] id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_dictinfo
     *
     * @mbggenerated
     */
    int insert(BbjDictinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_dictinfo
     *
     * @mbggenerated
     */
    int insertSelective(BbjDictinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_dictinfo
     *
     * @mbggenerated
     */
    List<BbjDictinfo> selectByExampleWithBLOBs(BbjDictinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_dictinfo
     *
     * @mbggenerated
     */
    List<BbjDictinfo> selectByExample(BbjDictinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_dictinfo
     *
     * @mbggenerated
     */
    BbjDictinfo selectByPrimaryKey(byte[] id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_dictinfo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BbjDictinfo record, @Param("example") BbjDictinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_dictinfo
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") BbjDictinfo record, @Param("example") BbjDictinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_dictinfo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BbjDictinfo record, @Param("example") BbjDictinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_dictinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BbjDictinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_dictinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(BbjDictinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_dictinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BbjDictinfo record);
}