package com.zhiao.blzc.test.dao;

import com.zhiao.blzc.test.entity.BbjZcPropertyPkg;
import com.zhiao.blzc.test.entity.BbjZcPropertyPkgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BbjZcPropertyPkgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_zc_property_pkg
     *
     * @mbggenerated
     */
    int countByExample(BbjZcPropertyPkgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_zc_property_pkg
     *
     * @mbggenerated
     */
    int deleteByExample(BbjZcPropertyPkgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_zc_property_pkg
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(byte[] id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_zc_property_pkg
     *
     * @mbggenerated
     */
    int insert(BbjZcPropertyPkg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_zc_property_pkg
     *
     * @mbggenerated
     */
    int insertSelective(BbjZcPropertyPkg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_zc_property_pkg
     *
     * @mbggenerated
     */
    List<BbjZcPropertyPkg> selectByExampleWithBLOBs(BbjZcPropertyPkgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_zc_property_pkg
     *
     * @mbggenerated
     */
    List<BbjZcPropertyPkg> selectByExample(BbjZcPropertyPkgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_zc_property_pkg
     *
     * @mbggenerated
     */
    BbjZcPropertyPkg selectByPrimaryKey(byte[] id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_zc_property_pkg
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BbjZcPropertyPkg record, @Param("example") BbjZcPropertyPkgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_zc_property_pkg
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") BbjZcPropertyPkg record, @Param("example") BbjZcPropertyPkgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_zc_property_pkg
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BbjZcPropertyPkg record, @Param("example") BbjZcPropertyPkgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_zc_property_pkg
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BbjZcPropertyPkg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_zc_property_pkg
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(BbjZcPropertyPkg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbj_zc_property_pkg
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BbjZcPropertyPkg record);
}